import os

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
PRODUCTION_KEY=os.environ.get('PRODUCTION_KEY')
print(EMAIL_HOST_USER, PRODUCTION_KEY)
