# Generated by Django 4.0.3 on 2022-04-22 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('cost', models.FloatField()),
                ('placement', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('last_time_used', models.DateTimeField(blank=True)),
                ('account', models.URLField(blank=True, verbose_name='associated account')),
                ('sold_price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('items', models.ManyToManyField(blank=True, to='Main.item')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='house name')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='state')),
                ('suburb', models.CharField(blank=True, max_length=200, verbose_name='suburb')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='street')),
                ('unit_number', models.CharField(blank=True, max_length=100, verbose_name='unit_number')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.house'),
        ),
    ]
