# Generated by Django 4.0.3 on 2022-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
