# Generated by Django 4.0.4 on 2022-06-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_category_description_alter_item_last_time_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='country',
            field=models.CharField(default='Australia/Sydney', max_length=200, verbose_name='country'),
        ),
    ]
