# Generated by Django 4.0.4 on 2022-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_house_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Sydney', max_length=200, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Australia', max_length=200, verbose_name='country'),
        ),
    ]
